export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
export const BEGING_API_CALL = 'BEGING_API_CALL';
export const API_CALL_ERROR = 'API_CALL_ERROR';
export const DELETE_COURSE = 'DELETE_COURSE';
